intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{renderdoc-app}: h{**} $intf_libs

# Build options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

c.poptions =+ "-I$out_pfx" "-I$src_pfx"

# Export options.
#
lib{renderdoc-app}:
{
  c.export.poptions = "-I$out_pfx" "-I$src_pfx"
  c.export.libs = $intf_libs
}

# Install recreating subdirectories.
#
h{*}:
{
  install         = include/
  install.subdirs = true
}
